config/routes.rb
Bonbon::Application.routes.draw do
  resources :apis

  

end

app/models/_api.rb
require "uri"
require "open-uri"
require "nokogiri"

class Api < ActiveRecord::Base
    def self.get_json
        data = []

        self.all.each do |api|
            imgs = []
            open("https://www.google.co.jp/search?q=#{URI.escape(api['keyword'])}&tbm=isch&biw=1306&bih=651", 'r') {|f|
              doc = Nokogiri.HTML f.read, nil, 'utf-8'
              doc.search('div#search a').each do |link|
                img = link.search('img')
                src = img[0].get_attribute('src')

                imgs << { 'href' => link.get_attribute('href'), 'src' => src }
              end
            }

            data << {'keyword' => api.keyword, 'name' => api.name, 'img' => imgs}
        end

        JSON.generate data
    end
end

app/models/api.rb
require "uri"
require "open-uri"
require "nokogiri"
require "json"

class Api < ActiveRecord::Base
  before_save :set_result_json

  def set_result_json
    img = []

    open("https://www.google.co.jp/search?q=#{URI.escape(self.keyword)}&tbm=isch&biw=1306&bih=1306", 'r') do |f|
      file = Nokogiri.HTML(f.read, nil, 'utf-8')
      file.search('div#search a').each do |link|
        img << { 'href' => link.get_attribute('href'), 'src' => link.search('img')[0].get_attribute('src') }
      end
    end

    self.result_json = JSON.generate img
  end
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  before_action :set_api, only: [:show, :edit, :update, :destroy]

  # GET /apis
  # GET /apis.json
  def index
    @apis = Api.all
    # respond_to do |format|
    #   format.html { @apis = Api.all }
    #   format.json { render :json => Api.get_json }
    # end
  end


  # GET /apis/1
  # GET /apis/1.json
  def show
  end

  # GET /apis/new
  def new
    @api = Api.new
  end

  # GET /apis/1/edit
  def edit
  end

  # POST /apis
  # POST /apis.json
  def create
    @api = Api.new(api_params)

    respond_to do |format|
      if @api.save
        format.html { redirect_to @api, notice: 'Api was successfully created.' }
        format.json { render action: 'show', status: :created, location: @api }
      else
        format.html { render action: 'new' }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apis/1
  # PATCH/PUT /apis/1.json
  def update
    respond_to do |format|
      if @api.update(api_params)
        format.html { redirect_to @api, notice: 'Api was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apis/1
  # DELETE /apis/1.json
  def destroy
    @api.destroy
    respond_to do |format|
      format.html { redirect_to apis_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api
      @api = Api.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def api_params
      params.require(:api).permit(:name, :keyword)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apis/_form.html.erb
<%= form_for(@api) do |f| %>
  <% if @api.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api.errors.count, "error") %> prohibited this api from being saved:</h2>

      <ul>
      <% @api.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :keyword %><br>
    <%= f.text_field :keyword %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apis/edit.html.erb
<h1>Editing api</h1>

<%= render 'form' %>

<%= link_to 'Show', @api %> |
<%= link_to 'Back', apis_path %>

app/views/apis/index.html.erb
<h1>Listing apis</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Keyword</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @apis.each do |api| %>
      <tr>
        <td><%= api.name %></td>
        <td><%= api.keyword %></td>
        <td><%= link_to 'Show', api %></td>
        <td><%= link_to 'Edit', edit_api_path(api) %></td>
        <td><%= link_to 'Destroy', api, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Api', new_api_path %>

app/views/apis/new.html.erb
<h1>New api</h1>

<%= render 'form' %>

<%= link_to 'Back', apis_path %>

app/views/apis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @api.name %>
</p>

<p>
  <strong>Keyword:</strong>
  <%= @api.keyword %>
</p>

<%= link_to 'Edit', edit_api_path(@api) %> |
<%= link_to 'Back', apis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bonbon</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>